[package]
name = "smoke-test"
version = "0.1.0"
description = "Smoke Test"

edition.workspace = true
authors.workspace = true

[dependencies]
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true

